name: gotip_driver
description: A new Flutter project for GOTIP Driver Web

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3

  google_fonts: ^6.2.1        
  http: ^1.2.0                
  shared_preferences: ^2.3.2  
  responsive_framework: ^1.5.0 
  intl: ^0.18.1               
  getwidget: ^4.0.0           
  device_info_plus: ^10.1.0   
  
  firebase_core: ^2.27.0
  firebase_messaging: ^14.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gotip_rmv.png
